"""Products add; UsersProducts secondary add

Revision ID: 125b4c3bb6a7
Revises: b70c6d256303
Create Date: 2026-03-21 17:55:16.939838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '125b4c3bb6a7'
down_revision: Union[str, Sequence[str], None] = 'b70c6d256303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('usersproducts',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('products_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'products_id')
    )
    op.add_column('users', sa.Column('product_id', sa.BigInteger(), nullable=False, constraint_name='foreign_key_users'))
    op.create_foreign_key(None, 'users', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'product_id')
    op.drop_table('usersproducts')
    op.drop_table('products')
    # ### end Alembic commands ###
