"""change wsfriendly column id became url_id

Revision ID: f3f9cb644ed3
Revises: 14ef5a41ccfd
Create Date: 2026-05-06 18:35:34.659239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f9cb644ed3'
down_revision: Union[str, Sequence[str], None] = '14ef5a41ccfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketfriendlymessage', sa.Column('from_user_url_id', sa.String(), nullable=True))
    op.add_column('websocketfriendlymessage', sa.Column('to_user_url_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_websocketfriendlymessage_to_user_id_users'), 'websocketfriendlymessage', type_='foreignkey')
    op.drop_constraint(op.f('fk_websocketfriendlymessage_from_user_id_users'), 'websocketfriendlymessage', type_='foreignkey')
    op.create_foreign_key(op.f('fk_websocketfriendlymessage_to_user_url_id_users'), 'websocketfriendlymessage', 'users', ['to_user_url_id'], ['url_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_websocketfriendlymessage_from_user_url_id_users'), 'websocketfriendlymessage', 'users', ['from_user_url_id'], ['url_id'], ondelete='CASCADE')
    op.drop_column('websocketfriendlymessage', 'to_user_id')
    op.drop_column('websocketfriendlymessage', 'from_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketfriendlymessage', sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('websocketfriendlymessage', sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_websocketfriendlymessage_from_user_url_id_users'), 'websocketfriendlymessage', type_='foreignkey')
    op.drop_constraint(op.f('fk_websocketfriendlymessage_to_user_url_id_users'), 'websocketfriendlymessage', type_='foreignkey')
    op.create_foreign_key(op.f('fk_websocketfriendlymessage_from_user_id_users'), 'websocketfriendlymessage', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_websocketfriendlymessage_to_user_id_users'), 'websocketfriendlymessage', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('websocketfriendlymessage', 'to_user_url_id')
    op.drop_column('websocketfriendlymessage', 'from_user_url_id')
    # ### end Alembic commands ###
