"""ws friendly - added a flag for read messages to conveniently display to the user

Revision ID: 8c7f744d0ff4
Revises: f3f9cb644ed3
Create Date: 2026-05-08 19:51:35.973057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7f744d0ff4'
down_revision: Union[str, Sequence[str], None] = 'f3f9cb644ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketfriendlymessage', sa.Column('is_read_message', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websocketfriendlymessage', 'is_read_message')
    # ### end Alembic commands ###
