"""add websocketfriendly for dialog messages

Revision ID: ba062fb68b3f
Revises: af0eea07aafc
Create Date: 2026-04-26 20:45:50.097104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba062fb68b3f"
down_revision: Union[str, Sequence[str], None] = "af0eea07aafc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websocketfriendlymessage",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("from_user_id", sa.Integer(), nullable=True),
        sa.Column("to_user_id", sa.Integer(), nullable=True),
        sa.Column("sender", sa.Text(), nullable=True),
        sa.Column("recipient", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "ws_friendly_type_message",
            sa.Enum(
                "bot", "recipient", "sender", "media", name="ws_friendly_type_message"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
            name=op.f("fk_websocketfriendlymessage_from_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.id"],
            name=op.f("fk_websocketfriendlymessage_to_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_websocketfriendlymessage")),
    )
    op.drop_constraint(op.f("products_description_key"), "products", type_="unique")
    op.create_unique_constraint(
        op.f("uq_products_description"), "products", ["description"]
    )
    op.drop_constraint(op.f("email_constraint"), "users", type_="unique")
    op.drop_constraint(op.f("phone_constraint"), "users", type_="unique")
    op.drop_constraint(op.f("users_password_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_url_id_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.create_unique_constraint(op.f("uq_users_password"), "users", ["password"])
    op.create_unique_constraint(op.f("uq_users_phone"), "users", ["phone"])
    op.create_unique_constraint(op.f("uq_users_url_id"), "users", ["url_id"])
    op.drop_constraint(
        op.f("websocketmessagehistory_from_user_id_fkey"),
        "websocketmessagehistory",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("websocketmessagehistory_to_user_id_fkey"),
        "websocketmessagehistory",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_websocketmessagehistory_to_user_id_users"),
        "websocketmessagehistory",
        "users",
        ["to_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_websocketmessagehistory_from_user_id_users"),
        "websocketmessagehistory",
        "users",
        ["from_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_websocketmessagehistory_from_user_id_users"),
        "websocketmessagehistory",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_websocketmessagehistory_to_user_id_users"),
        "websocketmessagehistory",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("websocketmessagehistory_to_user_id_fkey"),
        "websocketmessagehistory",
        "users",
        ["to_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("websocketmessagehistory_from_user_id_fkey"),
        "websocketmessagehistory",
        "users",
        ["from_user_id"],
        ["id"],
    )
    op.drop_constraint(op.f("uq_users_url_id"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_phone"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_password"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_url_id_key"),
        "users",
        ["url_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_password_key"),
        "users",
        ["password"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("phone_constraint"),
        "users",
        ["phone"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("email_constraint"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("uq_products_description"), "products", type_="unique")
    op.create_unique_constraint(
        op.f("products_description_key"),
        "products",
        ["description"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("websocketfriendlymessage")
    # ### end Alembic commands ###
