"""Products change;UsersProducts change; add fields for profile page

Revision ID: 674061152cbe
Revises: c3154e775dd7
Create Date: 2026-03-30 19:28:07.665660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "674061152cbe"
down_revision: Union[str, Sequence[str], None] = "c3154e775dd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.Text(), nullable=True))
    op.create_unique_constraint("phone_constraint", "users", ["phone"])
    op.create_unique_constraint("email_constraint", "users", ["email"])
    op.add_column(
        "usersproducts",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersproducts", "created_at")
    op.drop_constraint("email_constraint", "users", type_="unique")
    op.drop_constraint("phone_constraint", "users", type_="unique")
    op.drop_column("users", "phone")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
