"""Products change; add slug for query param

Revision ID: e8ba872bbfe4
Revises: ed357894f7e7
Create Date: 2026-03-23 10:54:54.165459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8ba872bbfe4"
down_revision: Union[str, Sequence[str], None] = "ed357894f7e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("slug", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "slug")
    # ### end Alembic commands ###
