"""Products change; change field price

Revision ID: 6867fe002307
Revises: e152e105bd89
Create Date: 2026-03-28 21:34:53.969667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6867fe002307'
down_revision: Union[str, Sequence[str], None] = 'e152e105bd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
