"""Products change; add field short_name

Revision ID: df48a74a4b37
Revises: 004a186c3d68
Create Date: 2026-03-22 17:21:58.897953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df48a74a4b37'
down_revision: Union[str, Sequence[str], None] = '004a186c3d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('short_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'short_name')
    # ### end Alembic commands ###
