"""change websocketfriendly field type

Revision ID: 14ef5a41ccfd
Revises: ba062fb68b3f
Create Date: 2026-04-28 17:25:22.696714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ef5a41ccfd'
down_revision: Union[str, Sequence[str], None] = 'ba062fb68b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketfriendlymessage', sa.Column('type_message', sa.Enum('bot', 'client', name='type_message'), nullable=False))
    op.drop_column('websocketfriendlymessage', 'ws_friendly_type_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketfriendlymessage', sa.Column('ws_friendly_type_message', postgresql.ENUM('bot', 'recipient', 'sender', 'media', name='ws_friendly_type_message'), autoincrement=False, nullable=False))
    op.drop_column('websocketfriendlymessage', 'type_message')
    # ### end Alembic commands ###
