"""Products change; add fields for auth

Revision ID: 273dc8e5b973
Revises: df48a74a4b37
Create Date: 2026-03-22 17:29:22.036426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '273dc8e5b973'
down_revision: Union[str, Sequence[str], None] = 'df48a74a4b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_registration', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('cookie', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cookie_expires', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now()) + interval '5 minutes'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cookie_expires')
    op.drop_column('users', 'cookie')
    op.drop_column('users', 'date_registration')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
