"""users add ip for content of weather

Revision ID: af0eea07aafc
Revises: 4b2fee8abf3c
Create Date: 2026-04-16 17:14:48.112919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0eea07aafc'
down_revision: Union[str, Sequence[str], None] = '4b2fee8abf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ip')
    # ### end Alembic commands ###
