"""Products change; del product_id

Revision ID: e7c09f6b65fa
Revises: 273dc8e5b973
Create Date: 2026-03-22 17:51:34.696321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c09f6b65fa'
down_revision: Union[str, Sequence[str], None] = '273dc8e5b973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_product_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_product_id_fkey'), 'users', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
