"""users add urr_id

Revision ID: 4b2fee8abf3c
Revises: e24ca4528a5a
Create Date: 2026-04-10 17:14:33.060429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2fee8abf3c'
down_revision: Union[str, Sequence[str], None] = 'e24ca4528a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['url_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'url_id')
    # ### end Alembic commands ###
