# ============================================
# ГЛОБАЛЬНЫЕ НАСТРОЙКИ
# ============================================
user nginx;
worker_processes auto;
# пути внутри контейнера nginx
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
    use epoll;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Логи
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;

    # Оптимизация
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    client_max_body_size 100M;

    # Сжатие
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript
               application/json application/javascript application/xml+rss
               image/svg+xml;

    # ============================================
    # ОСНОВНОЙ СЕРВЕР
    # ============================================
    server {
        listen 80;
        server_name clay-shop.ru;

        # ЭТОТ БЛОК НУЖЕН CERTBOT ДЛЯ ПРОВЕРКИ
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # ===== ФРОНТЕНД (статичные файлы) =====
        location / {
            proxy_pass http://frontend_app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # ===== API БЭКЕНДА =====
        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://backend_app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        location /docs {
            proxy_pass http://backend_app:8000/docs;
            proxy_set_header Host $host;
        }



        # ===== СТАТИКА =====
        location /static/ {
            alias /static/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}